### ISSUE TITLE
extra dependencies needed in project

### ISSUE THREAD

**Issue by bergvandenp** [BreadMoirai/github-release-gradle-plugin#11]
To get the plugin working, I need to add some dependencies in my project. That shouldn't be needed, but if I don't, I get classNotFound errors. What am I doing wrong?
```
classpath 'com.squareup.okhttp3:okhttp:3.12.0'
classpath 'com.j256.simplemagic:simplemagic:1.10'
classpath 'org.zeroturnaround:zt-exec:1.10'
```

**Comment by BreadMoirai** [comment]
I might be able to help you better if you upload your gradle build file

**Comment by BreadMoirai** [comment]
You may need to add an extra snippet to the top of your build.gradle file

```groovy
buildscript {
  repositories {
    jcenter()
  }
}
```

**Comment by bergvandenp** [comment]
thanks for the suggestion, but that doesn't work. This is the same issue as #9 
I think it's caused by the way the dependecies are decleared (`implementation`). 
https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html

**Comment by stewartbryson** [comment]
> You may need to add an extra snippet to the top of your build.gradle file
> 
> ```groovy
> buildscript {
>   repositories {
>     jcenter()
>   }
> }
> ```

Gradle does this be default... using jCenter to resolve dependencies.

I'm having issues resolving OkHttpClient, and the buildscript recommendation does not help. Any ideas?

`java.lang.NoClassDefFoundError: okhttp3/OkHttpClient`

**Comment by stewartbryson** [comment]
> thanks for the suggestion, but that doesn't work. This is the same issue as #9
> I think it's caused by the way the dependecies are decleared (`implementation`).
> https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html

I'm not sure about the change to `api` and `implementation`... I still use `compile` for most everything. I have tested using `implementation` with Gradle plugins and I see this issue. So I believe a simple `compile` would fix this. However... I'm not sure what the preferred approach is. Should it be `api` to create the transitive dependencies?

**Comment by kevinmmarlow** [comment]
Having the same problem. Not sure why the dependencies are not downloading from jcenter.

**Comment by duncte123** [comment]
I'm having the same issue with gradle 5.1.1 on version 2.2.3 on java 11

**Comment by BreadMoirai** [comment]
As per stewartbryson's recommendation, I have updated `2.2.4` to use `compile` instead of `implementation`
