### ISSUE TITLE
[feature request] Support Github Enterprise installations

### ISSUE THREAD

**Issue by mpern** [BreadMoirai/github-release-gradle-plugin#14]
It would be nice if the github URL wasn't hard-coded to `https://api.github.com` but configurable 😃

**Comment by BreadMoirai** [comment]
I've added a new property [`apiEndpoint`](https://github.com/BreadMoirai/github-release-gradle-plugin/wiki#apiEndpoint). Check the [README](https://github.com/BreadMoirai/github-release-gradle-plugin) for more info. Let me know if that works for you.
