### ISSUE TITLE
Could not create release: 307 Temporary Redirect

### ISSUE THREAD

**Issue by xaviarias** [BreadMoirai/github-release-gradle-plugin#27]
Hi, 

I get an error while running the task `githubRelease` in my local machine:

```
Execution failed for task ':web3j-corda-console:githubRelease'.
> Could not create release: 307 Temporary Redirect
  [message:Moved Permanently, url:https://api.github.com/repositories/216038060/releases, documentation_url:https://developer.github.com/v3/#http-redirects]
```

Is that a change in the GitHub API that needs to be reflected in the plugin ? Seems very unprovable.

Thanks

**Comment by BreadMoirai** [comment]
Hi,

I've added support for 307 redirects with the latest version `2.2.10`.
Let me know if you continue to encounter issues.
