### ISSUE TITLE
Add a dry run option

### ISSUE THREAD

**Issue by stewartbryson** [BreadMoirai/github-release-gradle-plugin#31]
It would be good if we could run a dry run without actually releasing. For instance, I’m currently having issues with my file filter not matching files, and the only way I can test is by actually creating a release. I would like to do a dry run where the plugin tells me which files it would add to the release.

**Comment by BreadMoirai** [comment]
Added in `2.2.11` as a property. Let me know if that works fine for you. [See here](https://github.com/BreadMoirai/github-release-gradle-plugin/wiki#dryRun)
