### ISSUE TITLE
Add a dry run option

### ISSUE THREAD

**Issue by stewartbryson** [BreadMoirai/github-release-gradle-plugin#33]
In order to test things like the file pattern, we have to actually trigger a GitHub release and see which files were attached.

A dry run option would be great. It cloud printo our the files that would be attached, and anything else that might be helpful.

**Comment by BreadMoirai** [comment]
Is the current dry run option insufficient for your purposes?

**Comment by stewartbryson** [comment]
Sorry... I missed that there was one. Let me check.

**Comment by stewartbryson** [comment]
I was expecting a `-P` option and completely missed the DSL for this. Sorry about that. FYI... I wrote a plugin that automatically searches for `-P` options that match DSL options in a plugin. Not sure if you would find it helpful. And also... unfortunately, I haven't documented it yet. 

Here's the plugin: https://github.com/RedPillAnalytics/gradle-properties

And here's another plugin where it is applied and used: https://github.com/RedPillAnalytics/gradle-confluent/blob/master/src/main/groovy/com/redpillanalytics/gradle/ConfluentPlugin.groovy
