### ISSUE TITLE
Defer the creation of githubRelease task

### ISSUE THREAD

**Issue by kyhule** [BreadMoirai/github-release-gradle-plugin#53]
I was poking around the code and noticed that the plugin is still using the `create` api to create the `githubRelease` task. Have you considered [deferring task creation](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:how_do_i_defer_creation) with the `register` api?

https://github.com/BreadMoirai/github-release-gradle-plugin/blob/4b33e9d61b09ca41e9d5dbb49a356e36d47e1b38/src/main/groovy/com/github/breadmoirai/githubreleaseplugin/GithubReleasePlugin.groovy#L37

**Comment by BreadMoirai** [comment]
Merged #60
