### ISSUE TITLE
Consider adding the possiblity to upload new files to an existing release

### ISSUE THREAD

**Issue by fthevenet** [BreadMoirai/github-release-gradle-plugin#7]
At the moment, when a release exists wit the same tag that the one you're trying to push, you've got the choice to either fail  or overwrite the release, deleting all attached asset.

This is an issue when the build process is distributed over several concurrent sessions, each responsible to upload its own set of files to a single github release.
In my case for instance, I use Travis CI to build a the same project on both linux and osx, as well as Appveyor to build on windows; each of these build being responsible to upload a platform specific binary distribution to the same GH release.

Because all these build run concurrently and it is not possible to predict which one will finish first, the required behaviour is that the first build to complete will create the release, while the other will be simply add new assets to it.

**Comment by BreadMoirai** [comment]
I've included your changes into version [`2.2.2-dev`](https://plugins.gradle.org/plugin/com.github.breadmoirai.github-release/2.2.2-dev). Let me know if your changes work for you.

**Comment by fthevenet** [comment]
Looking good. Thanks!
