### ISSUE TITLE
NoClassDefFoundError with Gradle 5.0

### ISSUE THREAD

**Issue by jmccance** [BreadMoirai/github-release-gradle-plugin#9]
Seeing a NoClassDefFoundError when trying to run under Grade 5.0. Looks like AbstractProvider was removed or renamed somewhere between 4.10.2 and 5.0.

These also appear to be unstable/internal APIs even in 5.0, so it might be worth exploring an alternative approach.

https://gist.github.com/jmccance/b9cf65834de2c4fbd82effc5c7728d86

**Comment by stewartbryson** [comment]
I'm seeing this as well.

**Comment by Xerus2000** [comment]
Same here, this is urgent! It prevents me from upgrading everything to gradle 5.0!

**Comment by BreadMoirai** [comment]
@akasolace Try adding this to the top of your build file
```gradle
buildscript {
  repositories {
    jcenter()
  }
} 
```

**Comment by akasolace** [comment]
I already have a 
`repositories {
    jcenter()
  }`

you want me to enclose this into a buildscript block? 
I can try but should I be aware of some side effects ?
